sudo: required
services:
    - docker

before_install:
    - docker build -t rishikant42/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true rishikant42/react-test npm run test

after_success:
    - docker build -t rishikant42/multi-client ./client
    - docker build -t rishikant42/multi-server ./server
    - docker build -t rishikant42/multi-worker ./worker
    - docker build -t rishikant42/multi-nginx ./nginx
    # Login to docker-CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take images & push them to docker hub
    - docker push rishikant42/multi-client
    - docker push rishikant42/multi-server
    - docker push rishikant42/multi-worker
    - docker push rishikant42/multi-nginx

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker-react
    env: MultiDockerReact-env
    bucket_name: elasticbeanstalk-us-east-2-472497218066
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
